# Generated by Django 5.2.7 on 2025-11-02 17:50

from django.db import migrations

def create_permissions_and_users(apps, schema_editor):
    # This function is intentionally left blank as a placeholder for future migration logic.
    from django.contrib.auth.models import User, Permission, Group
    # Future logic to create permissions and users can be added here.
    from django.contrib.contenttypes.models import ContentType
    # Example: content_type = ContentType.objects.get_for_model(YourModel)

    roles = ['Paciente', 'Doctor', 'Administrador']
    grupos = {}
    for role in roles:
        grupo, created = Group.objects.get_or_create(name=role)
        grupos[role] = grupo

    grupos['Administrador'].permissions.set(Permission.objects.all())
    # Additional permission assignments can be added here.
    
    grupos['paciente'].permissions.set(
        Permission.objects.get(codename='view_cita')),

    grupos['doctor'].permissions.set(
        Permission.objects.get(codename='view_cita, change_cita')),

#crear usuarios de prueba
    admin_user = User.objects.create_user(username='admin', password='adminpass')
    admin_user.groups.add(grupos['Administrador'])
    admin_user.is_staff = True
    admin_user.is_superuser = True
    admin_user.save()

    doctor_user = User.objects.create_user(username='doctor1', password='doctorpass')
    doctor_user.groups.add(grupos['Doctor'])
    doctor_user.save()

    paciente_user = User.objects.create_user(username='paciente1', password='pacientepass')
    paciente_user.groups.add(grupos['Paciente'])
    paciente_user.save()




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
    ]
