# Generated by Django 5.2.7 on 2025-11-02 17:50

from django.db import migrations

def create_permissions_and_users(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    User = apps.get_model('auth', 'User')

    # Crear grupos
    roles = ['Paciente', 'Doctor', 'Administrador']
    grupos = {}

    for role in roles:
        grupo, created = Group.objects.get_or_create(name=role)
        grupos[role] = grupo

    # Asignar permisos
    # Administrador → todos los permisos
    grupos['Administrador'].permissions.set(Permission.objects.all())

    # Paciente → solo ver citas
    permisos_paciente = Permission.objects.filter(
        codename='view_cita'
    )
    grupos['Paciente'].permissions.set(permisos_paciente)

    # Doctor → ver y cambiar citas
    permisos_doctor = Permission.objects.filter(
        codename__in=['view_cita', 'change_cita']
    )
    grupos['Doctor'].permissions.set(permisos_doctor)

    # Crear usuarios de prueba
    admin_user = User.objects.create_user(username='admin', password='adminpass')
    admin_user.groups.add(grupos['Administrador'])
    admin_user.is_staff = True
    admin_user.is_superuser = True
    admin_user.save()

    doctor_user = User.objects.create_user(username='doctor1', password='doctorpass')
    doctor_user.groups.add(grupos['Doctor'])

    paciente_user = User.objects.create_user(username='paciente1', password='pacientepass')
    paciente_user.groups.add(grupos['Paciente'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions_and_users),
    ]
